---
on:
  workflow_call:

jobs:
  markdown-link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Ensures we have the history to determine changed files
      - name: Fetch the base branch
        run: git fetch --depth=1 origin ${{ github.base_ref }}
      - name: Get changed markdown files
        id: get-changed-files
        run: |
          files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD -- '*.md')
          echo "files=$files" >> "$GITHUB_OUTPUT"
      - name: Install/run markdown link checker against changed markdown files
        run: |
          mds="${{ steps.get-changed-files.outputs.files }}"
          if [ ${#mds[@]} -ne 0 ]; then
            npm install -g markdown-link-check
            for mdf in "${mds[@]}"; do
                echo "Linkchecking $mdf ..."
                markdownlint "$mdf"
            done
          fi
      # - name: Check links in changed markdown files
      #   uses: gaurav-nelson/github-action-markdown-link-check@v1
      #   with:
      #     base-branch: ${{ github.base_ref }}
      #     check-modified-files-only: 'yes'
      #     # use-verbose-mode: 'yes'