---
on:
  workflow_call:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Ensures we have the history to determine changed files
      - name: Fetch the base branch
        run: git fetch --depth=1 origin ${{ github.base_ref }}
      - name: Get changed markdown files
        id: get-changed-files
        run: |
          files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD -- '*.md')
          echo "files=$files" >> "$GITHUB_OUTPUT"
      - name: Install/run markdown linter against changed markdown files
        run: |
          mds="${{ steps.get-changed-files.outputs.files }}"
          if [ ${#mds[@]} -ne 0 ]; then
            npm install -g markdownlint-cli
            for mdf in "${mds[@]}"; do
                echo "Linting $mdf ..."
                markdownlint "$mdf"
            done
          fi