---
on:
  workflow_call:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 2 # Ensures we have the history to determine changed files
      - name: Fetch the base branch
        run: git fetch --depth=1 origin ${{ github.base_ref }}
      - name: Get changed markdown files
        id: get-changed-files
        run: |
          files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD -- '*.md' | tr '\n' ' ')
          echo "files=$files" >> "$GITHUB_OUTPUT"
      - name: Markdown lint
        if: steps.get-changed-files.outputs.files != ''
        uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: ${{ steps.get-changed-files.outputs.files }}
