---
on:
  workflow_call:

jobs:
  enumerate_pkrvars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Enumerate iso
        env:
          EXCLUDE: 'amazonlinux-2.*|rhel.*|sles.*|solaris.*'
        shell: bash
        run: |
          mapfile -t < <(find os_pkrvars -name "*.pkrvars.hcl" | grep -Ev '(${{ env.EXCLUDE }})')
          echo "matrix=$(jq -cRn '[inputs]' < <( (( ${#MAPFILE[@]} )) && printf '%s\n' "${MAPFILE[@]}"))" >> "$GITHUB_OUTPUT"
        id: enumerate_pkrvars
    outputs:
      matrix: ${{ steps.enumerate_pkrvars.outputs.matrix }}

  iso-availability:
    needs: enumerate_pkrvars
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        template: ${{ fromJson(needs.enumerate_pkrvars.outputs.matrix) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: iso-availability
        shell: pwsh
        run: Invoke-RestMethod -Method Head -Verbose -Uri $(Get-Content '${{ matrix.template }}' | ConvertFrom-StringData).iso_url.Trim('"')
