---
on:
  workflow_call:

jobs:
  python-lint:
    runs-on: ubuntu-latest
    container: python:alpine
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      - name: Pull Change list
        id: changed-files
        uses: collin-miller/git-changesets@master
      - name: Verify Changed files
        id: verify-changed-files
        run: |
          echo '${{ steps.changed-files.outputs.added_modified }}' > changed.txt
          if grep ".*\.py" changed.txt; then
            echo "files_changed=true" >> $GITHUB_OUTPUT
          else
            echo "files_changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Run Python Lint
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          pip install --no-cache-dir boto boto3 pylint
          find . -type f -iname "*.py" -exec pylint \{\} \+
